version: "3.8"

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboard:/dashboard
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
#    command: run -o experimental-prometheus-rw /scripts/coupon/kafka-coupon-issue-load-test.js
#    command: run -o experimental-prometheus-rw /scripts/coupon/kafka-coupon-issue-peak-test.js
#    command: run -o experimental-prometheus-rw /scripts/coupon/kafka-coupon-issue-stress-test.js
#    command: run -o experimental-prometheus-rw /scripts/point/point-charge.k6.js
#    command: run -o experimental-prometheus-rw /scripts/order/order-payment-no-coupon.k6.js
#    command: run -o experimental-prometheus-rw /scripts/order/order-payment-no-coupon-load-test.k6.js
    command: run -o experimental-prometheus-rw /scripts/order/order-payment-no-coupon-peak-test.k6.js
#    command: run -o experimental-prometheus-rw /scripts/order/order-payment-no-coupon-stress-test.k6.js
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus

volumes:
  grafana_data: